name: Pipeline de integração Continua (CI)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: ["main", "master" ]
jobs:
  testes-e-validacao:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar Código-Fonte
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: instalar dependencias
        run: npm CI

      - name: Executar Linter
        run: npm run Lint

      - name: Executar Testes Automatizados
        run: npm test

      - name: Verificação de Segurança de Dependencias (SAST)
        run: npm audit --audit-level-high